[package]
name = "tokio-timer-segfault"
version = "0.1.0"
authors = ["Johannes Schoisswohl <johannes.sch@gmx.net>"]

[dependencies]
tokio-timer = { path = "tokio-timer" }
#futures = "0.1"
#slab = "0.3.0"
